### PR TITLE
some small fixes

### PR DESCRIPTION
**Pull request by proudcommerce**

### CODE REVIEW

**Comment by akleiber** [comment]
@proudcommerce thank you for the PR - what exactly does this fix?
This plugin is intended for Oxid 4/5 only - Oxid 6 can be found here https://github.com/8select/oxid6-plugin

What is Oxid 8.x?

**Comment by proudcommerce** [comment]
ups, i mean oxid 4.8 ;-)

**Comment by Wytrykus** [comment]
@proudcommerce Why exactly is oxcache only cleared for EE edition? Is oxcache not available for CE/PE? 
Actually we have the module running on CE editions and that's working fine, so it doesn't seem to cause an error - or the function is simply never called?

**Comment by tabsl** [comment]
> Is oxcache not available for CE/PE?
yes, only EE

> so it doesn't seem to cause an error - or the function is simply never called?
I don´t know. Have you tested?

**Comment by Wytrykus** [comment]
@tabsl Currently we rely on third parties for all the code of this module because we don't have the Oxid knowledge in-house, hence we have not tested it in an own test environment.

However, I've already tried to set up an Oxid CE with various Docker images for the Apache and MySQL, but never got the Apache settings right so that they're accepted by Oxid. Do you have a hint to a working Apache setup / Docker image that works with Oxid out-of-the-box?

**Comment by tabsl** [comment]
Working container for OXID 6: https://github.com/proudcommerce/docker-oxid6 (but not oxid 4/5) :-(

**Comment by Wytrykus** [comment]
@tabsl I know this Oxid 6 docker, I use it ;-) 
But do you know about any for Oxid 4/5?

**Comment by tabsl** [comment]
no, sorry. :-(

**Comment by akleiber** [comment]
Our Oxid plugin will be discontinued.

**Pull request closed without merging**
